apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  NEXT_PUBLIC_API_URL: {{ .Values.env.NEXT_PUBLIC_API_URL | quote }}
  APP_NAME: {{ .Values.env.APP_NAME | quote }}
