apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "frontend.fullname" . }}-role
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list"]
