apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frontend.fullname" . }}-secrets
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | b64enc | quote }}
