replicaCount: 1

image:
  repository: frontend
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: frontend.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

env:
  - name: API_URL
    value: "http://backend.dev.svc.cluster.local:5000"
